# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install build tools for native modules if needed
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy package definition and TypeScript config
COPY package*.json tsconfig.json ./

# Install dependencies (including dev for ts-node & typescript)
RUN npm install

# Copy source code
COPY src ./src

# Default command: run the MCP over stdio
CMD ["npx", "ts-node", "src/index.ts"]
